<a href="https://colab.research.google.com/github/Rojogenis/Empleos/blob/master/Copia_de_cripto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CALCULO MANUAL DE LA DETERMINATE PARA QUE SEA IGUAL A 1**

In [ ]:
#ASIGNAMOS LOS DAATOS DE LA MATRIZ
a11=1; a12=55;  a13=28
a21=0; a22=1; a23=35
a31=0; a32=0; a33=1

#TODOS LOS POSITIVOS
a=a11*a22*a33
b=a12*a23*a31
c=a13*a21*a32

#TODOS LOS NEGATIVOS
d=a13*a22*a31
e=a11*a23*a32
f=a12*a21*a33

#IMPORIMIMOS VALORES
print(a,b,c)
print(d,e,f)

1 0 0
0 0 0


**SE IMPRIMEN RESULTADOS DE LA DETERMINANTE**


In [ ]:
print(a+b+c)
print(-d-e-f)
print(a+b+c-d-e-f)

1
0
1


*SE ESCRIBE LA LLAVE EN FORMA DE MATRIZ**

In [ ]:
import numpy as np
llave =np.empty([3,3])

llave=np.array([
       [1, 56, 18,  8, 2 ],
       [0,  1,  5,  5, 7 ],
       [0,  0,  1, 28, 5 ],
       [0,  0,  0,  1, 3 ],
       [0,  0,  0,  0, 1 ]  
       ])

In [ ]:
llave

array([[ 1, 56, 18,  8,  2],
       [ 0,  1,  5,  5,  7],
       [ 0,  0,  1, 28,  5],
       [ 0,  0,  0,  1,  3],
       [ 0,  0,  0,  0,  1]])

**INTRODUCIMOS DATOS**

In [ ]:
count=0   #Este es para mandar el numero de veses que se repetira el ciclo
text =input ("Intriduce la frase a cifrar \n")                                             

#rellenamos la frase con espacios en blancos para poderla adaptar al tamaño de una matriz
while len(text)%len(llave[1,:]) !=0:                                               
  text=text+" "
 
  count = count + 1

  #Paramos en caso de quer falle 
  if  count> len(text):
    print("Error de logica")
    break

Intriduce la frase a cifrar 
Hola Jimmy


**SE CONVIERTEN TODOS LOS CARACTERES A ASCII PARA TRATARLOS**

In [ ]:
ascii_values = []
for character in text:
    ascii_values.append(ord(character))
print(ascii_values)

[72, 111, 108, 97, 32, 74, 105, 109, 109, 121]


**SE CONVIERTEN EN MATRIZ**

In [ ]:

j=0
ite=int(((len(ascii_values))/len(llave[1,:])))
y=len(llave[1,:])

In [ ]:
text=np.empty([ite,y])

In [ ]:
 j=0
 for i in range(ite):
  for e in range(y):
    print(i,",",e)
    text[i, e]=ascii_values[j]
    j=j+1

0 , 0
0 , 1
0 , 2
0 , 3
0 , 4
1 , 0
1 , 1
1 , 2
1 , 3
1 , 4


In [ ]:
ascii_values

[72, 111, 108, 97, 32, 74, 105, 109, 109, 121]

In [ ]:
text

array([[ 72., 111., 108.,  97.,  32.],
       [ 74., 105., 109., 109., 121.]])

**MULTIPLICAMOS LA MATRIZ POR LA LLAVE PARA ENCRIPTAR**

In [ ]:
msjcod=np.matmul(text,llave)

In [ ]:
msjcod

array([[  72., 4143., 1959., 4252., 1784.],
       [  74., 4249., 1966., 4278., 1876.]])

DESENCRIPTAMOS PARA MULTIPLICANDO EL MENSAJE CODIFICADO POR LA INVERSA DE LA MATRIZ

In [ ]:
msj0= np.matmul(msjcod,np.linalg.inv(llave))

GUARDAMOS LA FRASE EN UN STRING Y LO IMPRIMIMOS

In [ ]:
frase = ""
x=[]
j=0
for e in range(ite):
  for i in range(y):
    frase=frase+chr(int(msj0[e,i]))
print(frase)

Hola Jimmy


In [ ]:
msj0

array([[ 72., 111., 108.,  97.,  32.],
       [109., 117., 110., 100., 111.]])

[72, 111, 108, 97, 32, 109, 117, 110, 100, 111, 32, 32]